# Generated by Django 3.0.2 on 2021-01-13 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='', max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('data_publikacji', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
